CREATE TABLE bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank VARCHAR(30) NOT NULL,
    account_number VARCHAR(20) NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    currency_type VARCHAR(10) NOT NULL,
    account_balance NUMERIC(15,2) NOT NULL,
    owner_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uq_bank_account_number UNIQUE (account_number)
);