CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(15,2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    category VARCHAR(30) NOT NULL,
    mcc VARCHAR(4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    bank_account_id BIGINT NOT NULL,

    CONSTRAINT fk_txn_account FOREIGN KEY (bank_account_id)
        REFERENCES bank_account(id)
);